import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import HeaderComponent from '../components/header.component';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <HeaderComponent />
        </div>
        <h1 className="text-center mt-20 text-slate-800 dark:text-red-600">
          This is <a href="/">Genkidama</a>
        </h1>
      </main>
    </div>
  );
};

export default Home;
