import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';

import PostComponent from '../components/post.component';
import { useAuth } from '../hooks/auth';
import postsList from '../public/mocks/postsList.json';

const Home: NextPage = () => {
  const { user } = useAuth();
  const router = useRouter();

  if (!user) {
    router.push('sign-in');
    return null;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <div className="flex flex-col md:flex-row p-10">
          <div className="w-auto md:w-1/3 md:mr-16">
            {postsList.posts.map(post => {
              const { title, content } = post;
              return (
                <PostComponent title={title} content={content} key={post.id} />
              );
            })}
          </div>
          <div>
            Some other content in here: grafico bitcoin? Gatilhos? Operacoes
            abertas? Calendario de lives para membros? Give me more ideasss
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
